### ISSUE TITLE
NoClassDefFoundError: RepositoryInvokerFactory

### ISSUE THREAD

**Issue by lazaridis-com** [lazaridis-com/light-admin#6]
I've copied the spring-boot module into master, compiled, but the spring-boot fails in a similar way than it failed in an non-updated code.

@akurdyukov , sure this works on your side?

```
java.lang.NoClassDefFoundError: org/springframework/data/rest/core/invoke/RepositoryInvokerFactory
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.7.0_79]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615) ~[na:1.7.0_79]
        at java.lang.Class.getDeclaredMethods(Class.java:1860) ~[na:1.7.0_79]
        at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:140) ~[spring-core-4.1.6.RELEASE.jar:4.1
.6.RELEASE]
```

**Comment by lazaridis-com** [comment]
sorry, my fault, fixed with  023ac2d
